language: node_js

sudo: required

node_js:
    - 5.1
    - 6.0

env:
  - BROWSER='Chrome'
  - BROWSER='Firefox'
  - BROWSER='Opera'

before_install:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

before_script:
    - npm install
    - wget http://download1.operacdn.com/pub/opera/desktop/37.0.2178.32/linux/opera-stable_37.0.2178.32_amd64.deb
    - DEBIAN_FRONTEND=noninteractive sudo dpkg -i opera-stable_37.0.2178.32_amd64.deb

script: npm test
